
import java.util.Arrays;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dymoo6791
 */
public class mathFrame extends javax.swing.JFrame {

    /**
     * Creates new form mathFrame
     */
    public mathFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        maxBtn = new javax.swing.JButton();
        maxTF2 = new javax.swing.JTextField();
        maxTF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maxLbl = new javax.swing.JLabel();
        minTF1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        minTF2 = new javax.swing.JTextField();
        minBtn = new javax.swing.JButton();
        minLbl = new javax.swing.JLabel();
        expoTF = new javax.swing.JTextField();
        HypBtn = new javax.swing.JButton();
        hypLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sideTF2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valueTF = new javax.swing.JTextField();
        powBtn = new javax.swing.JButton();
        powLbl = new javax.swing.JLabel();
        sideTF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maxBtn.setText("Largest");
        maxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxBtnActionPerformed(evt);
            }
        });
        jPanel1.add(maxBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        maxTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxTF2ActionPerformed(evt);
            }
        });
        jPanel1.add(maxTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 60, -1));

        maxTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxTF1ActionPerformed(evt);
            }
        });
        jPanel1.add(maxTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Math Methods");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, -1));

        jLabel2.setText("Enter two numbers and click the button. The program will display the lowest number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        maxLbl.setText("------------------");
        jPanel1.add(maxLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 190, 20));

        minTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTF1ActionPerformed(evt);
            }
        });
        jPanel1.add(minTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, -1));

        jLabel3.setText("Enter two numbers and click the button. The program will display the largest number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        minTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTF2ActionPerformed(evt);
            }
        });
        jPanel1.add(minTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 60, -1));

        minBtn.setText("Smallest");
        minBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minBtnActionPerformed(evt);
            }
        });
        jPanel1.add(minBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        minLbl.setText("------------------");
        jPanel1.add(minLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 190, 20));

        expoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expoTFActionPerformed(evt);
            }
        });
        jPanel1.add(expoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 60, -1));

        HypBtn.setText("Hypotenuse");
        HypBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HypBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HypBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        hypLbl.setText("------------------");
        jPanel1.add(hypLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 190, 20));

        jLabel4.setText("Enter two numbers and click the button. The program will display the hypotenuse of a right angle triangle");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        sideTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideTF2ActionPerformed(evt);
            }
        });
        jPanel1.add(sideTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 60, -1));

        jLabel5.setText("Enter two numbers and click the button. The program will display the first value to the power of the second");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        valueTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTFActionPerformed(evt);
            }
        });
        jPanel1.add(valueTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, -1));

        powBtn.setText("To the power of");
        powBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powBtnActionPerformed(evt);
            }
        });
        jPanel1.add(powBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        powLbl.setText("------------------");
        jPanel1.add(powLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 190, 20));

        sideTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideTF1ActionPerformed(evt);
            }
        });
        jPanel1.add(sideTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maxTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxTF2ActionPerformed

    private void maxTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxTF1ActionPerformed

    private void maxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxBtnActionPerformed
        double max1 = Double.parseDouble(maxTF1.getText());
        double max2 = Double.parseDouble(maxTF2.getText());
        double solve = Math.max(max1, max2);
        String maxInt = String.valueOf(solve);
        maxLbl.setText(maxInt);
    }//GEN-LAST:event_maxBtnActionPerformed

    private void minTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minTF1ActionPerformed

    private void minTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minTF2ActionPerformed

    private void minBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBtnActionPerformed
        double min1 = Double.parseDouble(minTF1.getText());
        double min2 = Double.parseDouble(minTF2.getText());
        double solve = Math.min(min1, min2);
        String minInt = String.valueOf(solve);
        minLbl.setText(minInt);
    }//GEN-LAST:event_minBtnActionPerformed

    private void expoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expoTFActionPerformed

    private void HypBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HypBtnActionPerformed
        double side1 = Double.parseDouble(sideTF1.getText());
        double side2 = Double.parseDouble(sideTF2.getText());
        double solve = Math.hypot(side1, side2);
        double roundOff = Math.round(solve * 100.0) / 100.0;
        String hyp = String.valueOf(roundOff);
        hypLbl.setText(hyp);
    }//GEN-LAST:event_HypBtnActionPerformed

    private void valueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueTFActionPerformed

    private void sideTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideTF2ActionPerformed

    private void sideTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideTF1ActionPerformed

    private void powBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powBtnActionPerformed
        double value = Double.parseDouble(valueTF.getText());
        double expo = Double.parseDouble(expoTF.getText());
        double solve = Math.pow(value, expo);
        String total = String.valueOf(solve);
        powLbl.setText(total);
    }//GEN-LAST:event_powBtnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mathFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mathFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mathFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mathFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mathFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HypBtn;
    private javax.swing.JTextField expoTF;
    private javax.swing.JLabel hypLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maxBtn;
    private javax.swing.JLabel maxLbl;
    private javax.swing.JTextField maxTF1;
    private javax.swing.JTextField maxTF2;
    private javax.swing.JButton minBtn;
    private javax.swing.JLabel minLbl;
    private javax.swing.JTextField minTF1;
    private javax.swing.JTextField minTF2;
    private javax.swing.JButton powBtn;
    private javax.swing.JLabel powLbl;
    private javax.swing.JTextField sideTF1;
    private javax.swing.JTextField sideTF2;
    private javax.swing.JTextField valueTF;
    // End of variables declaration//GEN-END:variables
}
